// MODEL DATA — mockData.js
// 50+ Bangalore salons with unique images, rich services, gallery arrays

export const MOCK_SALONS = [
  // ── INDIRANAGAR (7 salons) ───────────────────────────────
  {
    id:"lakme-indiranagar", name:"Lakme Salon", branch:"Indiranagar", area:"Indiranagar",
    address:"100 Feet Road, HAL 2nd Stage, Indiranagar, Bangalore 560038",
    rating:4.8, reviewCount:312, priceRange:"2999",
    tags:["Hair","Bridal","Skin"],
    services:[
      {id:"s1",name:"Haircut & Styling",price:649,duration:45},
      {id:"s2",name:"Hair Spa",price:1599,duration:60},
      {id:"s3",name:"Keratin Treatment",price:5999,duration:180},
      {id:"s4",name:"Hair Colouring",price:2799,duration:120},
      {id:"s5",name:"Bridal Makeup",price:9999,duration:180},
      {id:"s6",name:"Lakme Facial",price:1299,duration:60},
      {id:"s7",name:"Manicure + Pedicure",price:999,duration:75},
    ],
    hours:"10:00 AM – 8:00 PM", phone:"+91 98860 11001",
    image: "/Images/Lakme.jpeg",
    gallery:["/Images/Lakme.jpeg","/Images/Lakme.jpeg","/Images/Lakme.jpeg"],
    about:"Bangalore's most trusted beauty destination with internationally trained stylists and award-winning bridal artists.",
    openNow:true,
  },
  {
    id:"bodycraft-indiranagar", name:"Bodycraft Spa & Salon", branch:"Indiranagar", area:"Indiranagar",
    address:"2nd A Main Road, Binnamangala Stage 1, Indiranagar, Bangalore 560038",
    rating:4.9, reviewCount:471, priceRange:"3999",
    tags:["Luxury","Skin","Hair","Spa"],
    services:[
      {id:"s1",name:"Signature Haircut",price:1299,duration:60},
      {id:"s2",name:"Dermalogica Facial",price:3499,duration:90},
      {id:"s3",name:"Body Massage (60 min)",price:2999,duration:60},
      {id:"s4",name:"Bridal Package",price:35000,duration:480},
      {id:"s5",name:"Hair Botox",price:6999,duration:180},
      {id:"s6",name:"Nail Art (10 nails)",price:1499,duration:75},
      {id:"s7",name:"Waxing (Full Body)",price:1799,duration:90},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22001",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"Bangalore's premier spa-salon chain. Dermatologist-led skin care, luxury spa treatments and award-winning bridal services.",
    openNow:true,
  },
  {
    id:"bblunt-indiranagar", name:"BBLUNT Salon", branch:"Indiranagar", area:"Indiranagar",
    address:"100 Feet Road, Indiranagar, Bangalore 560038",
    rating:4.8, reviewCount:189, priceRange:"2999",
    tags:["Luxury","Hair","Colour"],
    services:[
      {id:"s1",name:"Signature Cut",price:1499,duration:60},
      {id:"s2",name:"Balayage",price:5499,duration:180},
      {id:"s3",name:"Keratin Treatment",price:6999,duration:210},
      {id:"s4",name:"Hair Botox",price:5999,duration:180},
      {id:"s5",name:"Scalp Spa",price:1999,duration:60},
      {id:"s6",name:"Ombre Colour",price:4999,duration:150},
    ],
    hours:"11:00 AM – 8:00 PM", phone:"+91 98860 99002",
    image:"/Images/Blunt.jpeg",
    gallery:["Images/Blunt.jpeg","Images/Blunt.jpeg","Images/Blunt.jpeg"],
    about:"Celebrity-favourite salon. BBLUNT is synonymous with chic editorial hair styling and lived-in colour.",
    openNow:true,
  },
  {
    id:"alchemic-indiranagar", name:"Alchemic Beauty Studio", branch:"Indiranagar", area:"Indiranagar",
    address:"2nd A Main Road, Binnamangala, Stage 1, Indiranagar, Bangalore 560038",
    rating:4.9, reviewCount:471, priceRange:"3999",
    tags:["Luxury","Hair","Colour","Skin"],
    services:[
      {id:"s1",name:"Creative Haircut",price:1499,duration:60},
      {id:"s2",name:"Fantasy Colour",price:6999,duration:240},
      {id:"s3",name:"Balayage (Hand-Painted)",price:5999,duration:180},
      {id:"s4",name:"Scalp Ritual",price:2499,duration:75},
      {id:"s5",name:"Bridal Styling",price:14999,duration:300},
      {id:"s6",name:"Hair Gloss Treatment",price:3499,duration:90},
    ],
    hours:"10:00 AM – 8:00 PM", phone:"+91 98860 10006",
    image:"/Images/Alchemic.jpeg",
    gallery:["/Images/Alchemic.jpeg","/Images/Alchemic.jpeg","/Images/Alchemic.jpeg"],
    about:"Indiranagar's top-rated boutique studio for creative colour and editorial cuts. A cult favourite.",
    openNow:true,
  },
  {
    id:"blown-indiranagar", name:"Blown Salon", branch:"Indiranagar", area:"Indiranagar",
    address:"967, 12th Main Road, HAL 2nd Stage, Indiranagar, Bangalore 560008",
    rating:4.7, reviewCount:189, priceRange:"1999",
    tags:["Hair","Colour","Blowdry"],
    services:[
      {id:"s1",name:"Signature Blowdry",price:799,duration:45},
      {id:"s2",name:"Precision Cut",price:999,duration:50},
      {id:"s3",name:"Balayage",price:4999,duration:180},
      {id:"s4",name:"Keratin",price:5999,duration:180},
      {id:"s5",name:"Scalp Treatment",price:1799,duration:60},
      {id:"s6",name:"Hair Colour",price:2499,duration:120},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 10003",
    image:"/Images/Blown.jpeg",
    gallery:["/Images/Blown.jpeg","/Images/Blown.jpeg","/Images/Blown.jpeg"],
    about:"Indiranagar's cult salon known for stunning blowouts, creative colour work and a chic atmosphere.",
    openNow:true,
  },
  {
    id:"ylg-indiranagar", name:"YLG Salon", branch:"Indiranagar", area:"Indiranagar",
    address:"12th Main Road, Indiranagar, Bangalore 560038",
    rating:4.5, reviewCount:312, priceRange:"2499",
    tags:["Skin","Hair","Nails","Organic"],
    services:[
      {id:"s1",name:"YLG Signature Facial",price:1599,duration:75},
      {id:"s2",name:"Haircut + Blowdry",price:699,duration:50},
      {id:"s3",name:"Body Polishing",price:2499,duration:90},
      {id:"s4",name:"Hair Straightening",price:3999,duration:180},
      {id:"s5",name:"De-Tan Pack",price:999,duration:60},
      {id:"s6",name:"Gel Nail Art",price:999,duration:60},
    ],
    hours:"9:00 AM – 9:30 PM", phone:"+91 98860 33001",
    image:"/Images/YLG.jpeg",
    gallery:["/Images/YLG.jpeg","/Images/YLG.jpeg","/Images/YLG.jpeg"],
    about:"Bangalore-born YLG with skin-first philosophy and expert stylists for every beauty need.",
    openNow:true,
  },
  {
    id:"franck-indiranagar", name:"Franck Provost", branch:"Indiranagar", area:"Indiranagar",
    address:"100 Feet Road, HAL 2nd Stage, Indiranagar, Bangalore 560038",
    rating:4.8, reviewCount:167, priceRange:"1999",
    tags:["Luxury","Hair","Colour","Bridal"],
    services:[
      {id:"s1",name:"Parisian Haircut",price:1999,duration:60},
      {id:"s2",name:"Bespoke Colour",price:4999,duration:150},
      {id:"s3",name:"Balayage (Ombré)",price:5999,duration:180},
      {id:"s4",name:"Bridal Styling",price:14999,duration:300},
      {id:"s5",name:"Keratin Treatment",price:7499,duration:210},
      {id:"s6",name:"Hair Spa (Kérastase)",price:3499,duration:90},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 88001",
    image:"/Images/Provost.jpeg",
    gallery:["/Images/Provost.jpeg","/Images/Provost.jpeg","/Images/Provost.jpeg"],
    about:"40+ years of Parisian hair expertise. Franck Provost brings global runway looks to Bangalore.",
    openNow:true,
  },

  // ── KORAMANGALA (8 salons) ───────────────────────────────
  {
    id:"bodycraft-koramangala", name:"Bodycraft Spa & Salon", branch:"Koramangala", area:"Koramangala",
    address:"7th Block, Koramangala Industrial Area, Bangalore 560095",
    rating:4.8, reviewCount:389, priceRange:"1799",
    tags:["Luxury","Skin","Spa","Nails"],
    services:[
      {id:"s1",name:"Ainhoa Facial",price:3999,duration:90},
      {id:"s2",name:"Chocolate Spa Wrap",price:3499,duration:90},
      {id:"s3",name:"Gel Nail Extensions",price:1799,duration:90},
      {id:"s4",name:"Brazilian Blowout",price:8999,duration:210},
      {id:"s5",name:"Hair Colour (Global)",price:3999,duration:120},
      {id:"s6",name:"Body Massage",price:2999,duration:60},
      {id:"s7",name:"Waxing (Full Body)",price:1799,duration:90},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22002",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"Koramangala's luxury wellness destination with expert dermatologists, stylists and spa therapists.",
    openNow:true,
  },
  {
    id:"jcb-koramangala", name:"Jean-Claude Biguine", branch:"Koramangala", area:"Koramangala",
    address:"5th Block, 80 Feet Road, Koramangala, Bangalore 560095",
    rating:4.9, reviewCount:198, priceRange:"1299",
    tags:["Luxury","Hair","Colour"],
    services:[
      {id:"s1",name:"Signature Haircut",price:1299,duration:60},
      {id:"s2",name:"Balayage",price:5999,duration:180},
      {id:"s3",name:"Keratin Smoothening",price:6499,duration:210},
      {id:"s4",name:"Luxury Hair Spa",price:2499,duration:90},
      {id:"s5",name:"Ombre Colour",price:4999,duration:150},
      {id:"s6",name:"Scalp Detox",price:2999,duration:60},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 66001",
    image:"/Images/Biguine.jpeg",
    gallery:["/Images/Biguine.jpeg","/Images/Biguine.jpeg","/Images/Biguine.jpeg"],
    about:"French luxury salon brand with master colourists. Known for precision cuts and world-class colour.",
    openNow:true,
  },
  {
    id:"bblunt-koramangala", name:"BBLUNT Salon", branch:"Koramangala", area:"Koramangala",
    address:"Forum Mall, 5th Block, Koramangala, Bangalore 560095",
    rating:4.9, reviewCount:221, priceRange:"1499",
    tags:["Luxury","Hair","Colour","Bridal"],
    services:[
      {id:"s1",name:"The BBLUNT Cut",price:1499,duration:60},
      {id:"s2",name:"Feather Cut",price:1999,duration:75},
      {id:"s3",name:"Creative Colour",price:5499,duration:180},
      {id:"s4",name:"Bridal Styling",price:12999,duration:240},
      {id:"s5",name:"Hair Gloss Treatment",price:3499,duration:90},
      {id:"s6",name:"Smoothening",price:5999,duration:180},
    ],
    hours:"11:00 AM – 8:00 PM", phone:"+91 98860 99001",
    image:"/Images/Blunt.jpeg",
    gallery:["/Images/Blunt.jpeg","/Images/Blunt.jpeg","/Images/Blunt.jpeg"],
    about:"Celebrity-favourite salon from Mumbai — editorial cuts and lived-in colour.",
    openNow:true,
  },
  {
    id:"enrich-koramangala", name:"Enrich Salon", branch:"Koramangala", area:"Koramangala",
    address:"8th Block, Koramangala, Bangalore 560095",
    rating:4.4, reviewCount:278, priceRange:"1299",
    tags:["Skin","Hair","Nails"],
    services:[
      {id:"s1",name:"Bridal Makeup",price:14999,duration:240},
      {id:"s2",name:"Facial",price:1299,duration:60},
      {id:"s3",name:"Gel Nail Art",price:1299,duration:75},
      {id:"s4",name:"Keratin Treatment",price:4999,duration:180},
      {id:"s5",name:"Eyelash Extension",price:1999,duration:90},
      {id:"s6",name:"Hair Colour",price:2199,duration:120},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 55002",
    image:"/Images/Enrich.jpeg",
    gallery:["/Images/Enrich.jpeg","/Images/Enrich.jpeg","/Images/Enrich.jpeg"],
    about:"Modern express salon perfect for busy professionals. Walk-ins always welcome.",
    openNow:true,
  },
  {
    id:"jawed-koramangala", name:"Jawed Habib", branch:"Koramangala", area:"Koramangala",
    address:"5th Block, Koramangala, Bangalore 560095",
    rating:4.3, reviewCount:178, priceRange:"449",
    tags:["Hair","Colour","Men's"],
    services:[
      {id:"s1",name:"Haircut (Women)",price:849,duration:45},
      {id:"s2",name:"Haircut (Men)",price:549,duration:35},
      {id:"s3",name:"Beard Grooming",price:449,duration:30},
      {id:"s4",name:"Global Colour",price:2999,duration:120},
      {id:"s5",name:"Keratin",price:4799,duration:180},
      {id:"s6",name:"Hair Spa",price:1299,duration:60},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 10002",
    image:"/Images/Jawed habib.jpeg",
    gallery:["/Images/Jawed habib.jpeg","/Images/Jawed habib.jpeg","/Images/Jawed habib.jpeg"],
    about:"India's leading hair expert brand. Certified stylists from the Jawed Habib Academy.",
    openNow:true,
  },
  {
    id:"ylg-koramangala", name:"YLG Salon", branch:"Koramangala", area:"Koramangala",
    address:"8th Block, Koramangala, Bangalore 560095",
    rating:4.5, reviewCount:224, priceRange:"699",
    tags:["Skin","Hair","Nails","Organic"],
    services:[
      {id:"s1",name:"YLG Signature Facial",price:1599,duration:75},
      {id:"s2",name:"Haircut + Blowdry",price:699,duration:50},
      {id:"s3",name:"Gel Nails",price:999,duration:60},
      {id:"s4",name:"Balayage",price:3999,duration:150},
      {id:"s5",name:"Full Body Waxing",price:1299,duration:90},
      {id:"s6",name:"De-Tan Pack",price:999,duration:60},
    ],
    hours:"9:00 AM – 9:30 PM", phone:"+91 98860 33005",
    image:"/Images/YLG.jpeg",
    gallery:["/Images/YLG.jpeg","/Images/YLG.jpeg","/Images/YLG.jpeg"],
    about:"YLG Koramangala — the go-to for smart, skin-first beauty care for young professionals.",
    openNow:true,
  },
  {
    id:"franck-jayanagar", name:"Franck Provost", branch:"Jayanagar", area:"Jayanagar",
    address:"4th Block, Jayanagar, Bangalore 560041",
    rating:4.7, reviewCount:134, priceRange:"1999",
    tags:["Luxury","Hair","Colour"],
    services:[
      {id:"s1",name:"Haircut + Blowdry",price:1999,duration:60},
      {id:"s2",name:"Balayage",price:5999,duration:180},
      {id:"s3",name:"Hair Spa (Kérastase)",price:3499,duration:90},
      {id:"s4",name:"Lash Extension",price:2499,duration:90},
      {id:"s5",name:"Global Colour",price:3999,duration:120},
      {id:"s6",name:"Smoothening",price:5499,duration:180},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 88002",
    image:"/Images/Provost.jpeg",
    gallery:["/Images/Provost.jpeg","/Images/Provost.jpeg","/Images/Provost.jpeg"],
    about:"French precision cuts and colour at Franck Provost Jayanagar boutique salon.",
    openNow:true,
  },
  {
    id:"naturals-btm", name:"Naturals Salon", branch:"BTM Layout", area:"BTM Layout",
    address:"2nd Stage, BTM Layout, Bangalore 560076",
    rating:4.4, reviewCount:312, priceRange:"129",
    tags:["Organic","Hair","Skin"],
    services:[
      {id:"s1",name:"Herbal Facial",price:799,duration:60},
      {id:"s2",name:"Hair Cut + Style",price:449,duration:40},
      {id:"s3",name:"Waxing (Arms + Legs)",price:599,duration:50},
      {id:"s4",name:"Hair Spa",price:899,duration:60},
      {id:"s5",name:"Manicure + Pedicure",price:699,duration:60},
      {id:"s6",name:"Threading (Full Face)",price:129,duration:20},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 44002",
    image:"/Images/Naturals.jpeg",
    gallery:["/Images/Naturals.jpeg","/Images/Naturals.jpeg","/Images/Naturals.jpeg"],
    about:"Trusted organic salon with loyal regulars and affordable quality services.",
    openNow:true,
  },

  // ── JAYANAGAR (4 salons) ────────────────────────────────
  {
    id:"bodycraft-jayanagar", name:"Bodycraft Spa & Salon", branch:"Jayanagar", area:"Jayanagar",
    address:"10/1, Mariyappa Road, 1st Block, Jayanagar, Bangalore 560011",
    rating:4.7, reviewCount:267, priceRange:"1499",
    tags:["Luxury","Skin","Spa","Bridal"],
    services:[
      {id:"s1",name:"Bridal Makeup",price:29999,duration:480},
      {id:"s2",name:"Ayurvedic Body Massage",price:2999,duration:60},
      {id:"s3",name:"Keratin Treatment",price:6499,duration:180},
      {id:"s4",name:"Eyelash Extensions",price:2199,duration:90},
      {id:"s5",name:"Nail Art (10 nails)",price:1499,duration:75},
      {id:"s6",name:"Dermalogica Facial",price:3499,duration:90},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 22004",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"Jayanagar's top luxury spa and salon — known for bridal packages and premium skin treatments.",
    openNow:false,
  },
  {
    id:"naturals-jayanagar", name:"Naturals Salon", branch:"Jayanagar", area:"Jayanagar",
    address:"11th Main Road, 4th Block, Jayanagar, Bangalore 560041",
    rating:4.6, reviewCount:427, priceRange:"129",
    tags:["Organic","Hair","Skin"],
    services:[
      {id:"s1",name:"Organic Facial",price:899,duration:60},
      {id:"s2",name:"Aloe Hair Pack",price:699,duration:45},
      {id:"s3",name:"Haircut + Blowdry",price:499,duration:50},
      {id:"s4",name:"Full Face Threading",price:129,duration:20},
      {id:"s5",name:"Full Body Waxing",price:1199,duration:90},
      {id:"s6",name:"Henna Application",price:499,duration:45},
    ],
    hours:"9:30 AM – 8:30 PM", phone:"+91 98860 44001",
    image:"/Images/Naturals.jpeg",
    gallery:["/Images/Naturals.jpeg","/Images/Naturals.jpeg","/Images/Naturals.jpeg"],
    about:"100% natural and organic treatments using herbs, plant extracts and cruelty-free products.",
    openNow:false,
  },
  {
    id:"lakme-jayanagar", name:"Lakme Salon", branch:"Jayanagar", area:"Jayanagar",
    address:"11th Main Road, 4th Block, Jayanagar, Bangalore 560041",
    rating:4.6, reviewCount:198, priceRange:"649",
    tags:["Hair","Skin","Bridal"],
    services:[
      {id:"s1",name:"Haircut & Styling",price:649,duration:45},
      {id:"s2",name:"Lakme Facial",price:1299,duration:60},
      {id:"s3",name:"Manicure + Pedicure",price:999,duration:75},
      {id:"s4",name:"Waxing (Full Body)",price:1199,duration:90},
      {id:"s5",name:"Keratin Treatment",price:5999,duration:180},
      {id:"s6",name:"Bridal Makeup",price:9999,duration:180},
    ],
    hours:"10:00 AM – 8:00 PM", phone:"+91 98860 11003",
    image:"/Images/Lakme.jpeg",
    gallery:["/Images/Lakme.jpeg","/Images/Lakme.jpeg","/Images/Lakme.jpeg"],
    about:"A beloved Jayanagar institution serving the community with premium Lakme beauty services.",
    openNow:false,
  },
  {
    id:"naturals-banashankari", name:"Naturals Salon", branch:"Banashankari", area:"Banashankari",
    address:"2nd Stage, Banashankari, Bangalore 560070",
    rating:4.3, reviewCount:189, priceRange:"60",
    tags:["Organic","Hair","Skin"],
    services:[
      {id:"s1",name:"Organic Facial",price:899,duration:60},
      {id:"s2",name:"Haircut",price:399,duration:35},
      {id:"s3",name:"Henna Application",price:499,duration:45},
      {id:"s4",name:"Threading (Eyebrows)",price:60,duration:10},
      {id:"s5",name:"Hair Colour (Herbal)",price:999,duration:60},
      {id:"s6",name:"Head Massage",price:349,duration:30},
    ],
    hours:"9:30 AM – 8:30 PM", phone:"+91 98860 44003",
    image:"/Images/Naturals.jpeg",
    gallery:["/Images/Naturals.jpeg","/Images/Naturals.jpeg","/Images/Naturals.jpeg"],
    about:"Natural beauty at its finest — Banashankari's favourite budget-friendly organic salon.",
    openNow:true,
  },

  // ── MG ROAD (4 salons) ──────────────────────────────────
  {
    id:"bodycraft-lavelle", name:"Bodycraft Spa & Salon", branch:"Lavelle Road", area:"MG Road",
    address:"No. 52–53, Lavelle Road, Ashok Nagar, Bangalore 560001",
    rating:4.8, reviewCount:298, priceRange:"999",
    tags:["Luxury","Hair","Skin","Nails"],
    services:[
      {id:"s1",name:"Precision Haircut",price:1499,duration:60},
      {id:"s2",name:"Gel Manicure",price:999,duration:60},
      {id:"s3",name:"Anti-Ageing Facial",price:4999,duration:90},
      {id:"s4",name:"Brazilian Blowout",price:8999,duration:210},
      {id:"s5",name:"Eyelash Extensions",price:2499,duration:90},
      {id:"s6",name:"Body Massage",price:2999,duration:60},
    ],
    hours:"10:30 AM – 9:00 PM", phone:"+91 98860 22007",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"Bodycraft's flagship MG Road location — a premium urban salon experience in the city's heart.",
    openNow:true,
  },
  {
    id:"toni-guy-mgroad", name:"Toni & Guy", branch:"MG Road", area:"MG Road",
    address:"Brigade Road, Near Trinity Circle, Bangalore 560001",
    rating:4.7, reviewCount:284, priceRange:"1200",
    tags:["Luxury","Hair","Colour"],
    services:[
      {id:"s1",name:"Precision Cut (Women)",price:1800,duration:60},
      {id:"s2",name:"Precision Cut (Men)",price:1200,duration:45},
      {id:"s3",name:"Global Colour",price:3500,duration:120},
      {id:"s4",name:"Hair Botox",price:7999,duration:180},
      {id:"s5",name:"Brazilian Blowout",price:8999,duration:210},
      {id:"s6",name:"Scalp Treatment",price:1999,duration:60},
    ],
    hours:"10:30 AM – 9:00 PM", phone:"+91 98860 77001",
    image:"/Images/Toni&Guy.jpeg",
    gallery:["/Images/Toni&Guy.jpeg","/Images/Toni&Guy.jpeg","/Images/Toni&Guy.jpeg"],
    about:"Iconic British salon brand. Precision haircuts, advanced colour services and luxury treatments.",
    openNow:true,
  },
  {
    id:"jcb-ubcity", name:"Jean-Claude Biguine", branch:"UB City", area:"MG Road",
    address:"UB City Mall, Vittal Mallya Road, Bangalore 560001",
    rating:4.8, reviewCount:156, priceRange:"1499",
    tags:["Luxury","Hair","Colour","Bridal"],
    services:[
      {id:"s1",name:"Parisian Haircut",price:1499,duration:60},
      {id:"s2",name:"French Balayage",price:6499,duration:180},
      {id:"s3",name:"Bridal Hair Styling",price:12999,duration:240},
      {id:"s4",name:"Hair Gloss Treatment",price:3499,duration:90},
      {id:"s5",name:"Scalp Detox",price:2999,duration:60},
      {id:"s6",name:"Lash Extension",price:2499,duration:90},
    ],
    hours:"11:00 AM – 9:00 PM", phone:"+91 98860 66002",
    image:"/Images/Biguine.jpeg",
    gallery:["/Images/Biguine.jpeg","/Images/Biguine.jpeg","/Images/Biguine.jpeg"],
    about:"Haute couture hair at UB City Mall — JCB's most exclusive Bangalore location.",
    openNow:true,
  },
  {
    id:"blown-vml", name:"Blown Salon", branch:"Vittal Mallya Road", area:"MG Road",
    address:"Embassy Chambers, Vittal Mallya Road, Bangalore 560001",
    rating:4.8, reviewCount:134, priceRange:"1299",
    tags:["Luxury","Hair","Colour"],
    services:[
      {id:"s1",name:"Luxury Blowdry",price:1299,duration:60},
      {id:"s2",name:"Precision Cut",price:1499,duration:60},
      {id:"s3",name:"Balayage",price:5999,duration:180},
      {id:"s4",name:"Hair Botox",price:5999,duration:180},
      {id:"s5",name:"Colour Correction",price:7999,duration:240},
      {id:"s6",name:"Olaplex Treatment",price:1999,duration:90},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 10004",
    image:"/Images/Blown.jpeg",
    gallery:["/Images/Blown.jpeg","/Images/Blown.jpeg","/Images/Blown.jpeg"],
    about:"Premium Blown location on Vittal Mallya Road — go-to for colour correction and lived-in looks.",
    openNow:true,
  },

  // ── WHITEFIELD (3 salons) ───────────────────────────────
  {
    id:"bodycraft-whitefield", name:"Bodycraft Spa & Salon", branch:"Whitefield", area:"Whitefield",
    address:"Adjacent to Forum Value Mall, Whitefield Main Road, Bangalore 560066",
    rating:4.7, reviewCount:234, priceRange:"1799",
    tags:["Luxury","Hair","Skin","Spa"],
    services:[
      {id:"s1",name:"Hair Botox",price:6999,duration:180},
      {id:"s2",name:"Body Polish",price:3499,duration:90},
      {id:"s3",name:"Ainhoa Anti-Ageing Facial",price:4999,duration:90},
      {id:"s4",name:"Balayage",price:5999,duration:180},
      {id:"s5",name:"Hot Stone Massage",price:3499,duration:90},
      {id:"s6",name:"Nail Extensions",price:1799,duration:90},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22005",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"Luxurious Bodycraft in Whitefield offering world-class spa, hair and skin services.",
    openNow:true,
  },
  {
    id:"mirrors-whitefield", name:"Mirrors Luxury Salon", branch:"Whitefield", area:"Whitefield",
    address:"ITPL Main Road, Whitefield, Bangalore 560066",
    rating:4.8, reviewCount:156, priceRange:"1799",
    tags:["Luxury","Bridal","Skin","Nails"],
    services:[
      {id:"s1",name:"Luxury Facial (90 min)",price:2999,duration:90},
      {id:"s2",name:"Bridal Package (Full Day)",price:29999,duration:480},
      {id:"s3",name:"Nail Art (10 nails)",price:1799,duration:75},
      {id:"s4",name:"Eyebrow Microblading",price:7999,duration:120},
      {id:"s5",name:"Eyelash Extensions",price:2199,duration:90},
      {id:"s6",name:"Body Massage",price:2999,duration:60},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 10009",
    image:"/Images/Mirrors.jpeg",
    gallery:["/Images/Mirrors.jpeg","/Images/Mirrors.jpeg","/Images/Mirrors.jpeg"],
    about:"Award-winning luxury salon for Whitefield's discerning clientele. Stunning bridal transformations.",
    openNow:true,
  },
  {
    id:"lakme-whitefield", name:"Lakme Salon", branch:"Whitefield", area:"Whitefield",
    address:"ITPL Main Road, Whitefield, Bangalore 560066",
    rating:4.5, reviewCount:156, priceRange:"649",
    tags:["Hair","Skin","Nails"],
    services:[
      {id:"s1",name:"Haircut & Styling",price:649,duration:45},
      {id:"s2",name:"Gel Nail Art",price:1299,duration:75},
      {id:"s3",name:"Lakme Facial",price:1299,duration:60},
      {id:"s4",name:"Hair Colour",price:1999,duration:90},
      {id:"s5",name:"Hair Spa",price:1599,duration:60},
      {id:"s6",name:"Smoothening",price:4999,duration:180},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 11004",
    image:"/Images/Lakme.jpeg",
    gallery:["/Images/Lakme.jpeg","/Images/Lakme.jpeg","/Images/Lakme.jpeg"],
    about:"Serving Whitefield's IT professionals with premium beauty services and express appointment slots.",
    openNow:true,
  },

  // ── HSR LAYOUT (4 salons) ───────────────────────────────
  {
    id:"bodycraft-hsrlayout", name:"Bodycraft Spa & Salon", branch:"HSR Layout", area:"HSR Layout",
    address:"27th Main Road, Sector 2, HSR Layout, Bangalore 560102",
    rating:4.8, reviewCount:312, priceRange:"1799",
    tags:["Luxury","Skin","Hair","Spa"],
    services:[
      {id:"s1",name:"Olaplex Hair Treatment",price:1999,duration:90},
      {id:"s2",name:"Dermalogica Facial",price:3499,duration:90},
      {id:"s3",name:"Full Body Waxing",price:1799,duration:90},
      {id:"s4",name:"Manicure + Pedicure Spa",price:1599,duration:90},
      {id:"s5",name:"Swedish Massage",price:2499,duration:60},
      {id:"s6",name:"Smoothening",price:5999,duration:180},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22003",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"Flagship Bodycraft HSR — a full-service spa and salon destination in South Bangalore.",
    openNow:true,
  },
  {
    id:"lakme-hsrlayout", name:"Lakme Salon", branch:"HSR Layout", area:"HSR Layout",
    address:"Sector 1, 27th Main Road, HSR Layout, Bangalore 560102",
    rating:4.6, reviewCount:221, priceRange:"699",
    tags:["Hair","Skin","Bridal"],
    services:[
      {id:"s1",name:"Haircut & Blowdry",price:699,duration:50},
      {id:"s2",name:"Bridal Makeup",price:9999,duration:180},
      {id:"s3",name:"Facial",price:1299,duration:60},
      {id:"s4",name:"Smoothening",price:4999,duration:180},
      {id:"s5",name:"Nail Extensions",price:1499,duration:90},
      {id:"s6",name:"Hair Colour",price:2799,duration:120},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 11005",
    image:"/Images/Lakme.jpeg",
    gallery:["/Images/Lakme.jpeg","/Images/Lakme.jpeg","/Images/Lakme.jpeg"],
    about:"One of HSR Layout's top-rated beauty destinations. Expert bridal and skin care services.",
    openNow:true,
  },
  {
    id:"enrich-hsrlayout", name:"Enrich Salon", branch:"HSR Layout", area:"HSR Layout",
    address:"Sector 1, 27th Main Road, HSR Layout, Bangalore 560102",
    rating:4.5, reviewCount:339, priceRange:"899",
    tags:["Skin","Hair","Nails"],
    services:[
      {id:"s1",name:"Classic Facial",price:1299,duration:60},
      {id:"s2",name:"Gel Nails",price:999,duration:60},
      {id:"s3",name:"Eyelash Extension",price:1999,duration:90},
      {id:"s4",name:"Hair Colour",price:2199,duration:120},
      {id:"s5",name:"Foot Spa",price:899,duration:45},
      {id:"s6",name:"Waxing (Full Body)",price:1299,duration:90},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 55001",
    image:"/Images/Enrich.jpeg",
    gallery:["/Images/Enrich.jpeg","/Images/Enrich.jpeg","/Images/Enrich.jpeg"],
    about:"Modern express salon — perfect for busy professionals. Walk-ins always welcome.",
    openNow:true,
  },
  {
    id:"ylg-hsrlayout", name:"YLG Salon", branch:"HSR Layout", area:"HSR Layout",
    address:"BTM 2nd Stage, HSR Layout, Bangalore 560076",
    rating:4.4, reviewCount:198, priceRange:"599",
    tags:["Skin","Hair","Nails"],
    services:[
      {id:"s1",name:"Facial (Glow)",price:1399,duration:60},
      {id:"s2",name:"Haircut + Style",price:599,duration:45},
      {id:"s3",name:"Waxing (Full Body)",price:1299,duration:90},
      {id:"s4",name:"Manicure + Pedicure",price:999,duration:75},
      {id:"s5",name:"Hair Colour",price:1999,duration:90},
      {id:"s6",name:"Body Polishing",price:2499,duration:90},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 33003",
    image:"/Images/YLG.jpeg",
    gallery:["/Images/YLG.jpeg","/Images/YLG.jpeg","/Images/YLG.jpeg"],
    about:"A favourite among HSR Layout residents for affordable skin and hair care.",
    openNow:true,
  },

  // ── MALLESHWARAM (3 salons) ─────────────────────────────
  {
    id:"jawed-malleshwaram", name:"Jawed Habib", branch:"Malleshwaram", area:"Malleshwaram",
    address:"8th Cross, Sampige Road, Malleshwaram, Bangalore 560003",
    rating:4.4, reviewCount:211, priceRange:"449",
    tags:["Hair","Colour","Men's"],
    services:[
      {id:"s1",name:"Signature Haircut",price:849,duration:45},
      {id:"s2",name:"Beard Grooming",price:449,duration:30},
      {id:"s3",name:"Balayage",price:3799,duration:150},
      {id:"s4",name:"Smoothening",price:4799,duration:180},
      {id:"s5",name:"Scalp Treatment",price:1099,duration:45},
      {id:"s6",name:"Hair Colour",price:2499,duration:120},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 10001",
    image:"/Images/Jawed habib.jpeg",
    gallery:["/Images/Jawed habib.jpeg","/Images/Jawed habib.jpeg","/Images/Jawed habib.jpeg"],
    about:"India's leading hair expert brand. Certified stylists from the Jawed Habib Academy.",
    openNow:false,
  },
  {
    id:"lakme-malleshwaram", name:"Lakme Salon", branch:"Malleshwaram", area:"Malleshwaram",
    address:"8th Cross, Sampige Road, Malleshwaram, Bangalore 560003",
    rating:4.5, reviewCount:187, priceRange:"549",
    tags:["Hair","Skin","Bridal"],
    services:[
      {id:"s1",name:"Haircut & Styling",price:649,duration:45},
      {id:"s2",name:"Facial (Radiance)",price:1399,duration:60},
      {id:"s3",name:"Hair Colour",price:1999,duration:90},
      {id:"s4",name:"Waxing (Arms + Legs)",price:699,duration:50},
      {id:"s5",name:"Manicure",price:549,duration:40},
      {id:"s6",name:"Bridal Makeup",price:9999,duration:180},
    ],
    hours:"10:00 AM – 8:00 PM", phone:"+91 98860 11006",
    image:"/Images/Lakme.jpeg",
    gallery:["/Images/Lakme.jpeg","/Images/Lakme.jpeg","/Images/Lakme.jpeg"],
    about:"Trusted Lakme salon in old Malleshwaram, serving families with quality beauty care.",
    openNow:true,
  },
  {
    id:"naturals-malleshwaram", name:"Naturals Salon", branch:"Malleshwaram", area:"Malleshwaram",
    address:"15th Cross, Malleshwaram, Bangalore 560003",
    rating:4.4, reviewCount:211, priceRange:"249",
    tags:["Organic","Hair","Skin","Men's"],
    services:[
      {id:"s1",name:"Organic Facial",price:899,duration:60},
      {id:"s2",name:"Haircut (Men)",price:249,duration:30},
      {id:"s3",name:"Haircut (Women)",price:449,duration:40},
      {id:"s4",name:"Waxing (Full Body)",price:1199,duration:90},
      {id:"s5",name:"Head Massage",price:349,duration:30},
      {id:"s6",name:"Hair Spa",price:899,duration:60},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 44004",
    image:"/Images/Naturals.jpeg",
    gallery:["/Images/Naturals.jpeg","/Images/Naturals.jpeg","/Images/Naturals.jpeg"],
    about:"A family favourite in Malleshwaram — organic, affordable and consistently excellent.",
    openNow:true,
  },

  // ── ELECTRONIC CITY (2 salons) ──────────────────────────
  {
    id:"ylg-electroniccity", name:"YLG Salon", branch:"Electronic City", area:"Electronic City",
    address:"Phase 1, Neeladri Road, Electronic City, Bangalore 560100",
    rating:4.5, reviewCount:267, priceRange:"129",
    tags:["Skin","Hair","Nails"],
    services:[
      {id:"s1",name:"YLG Signature Facial",price:1599,duration:75},
      {id:"s2",name:"Nail Extensions",price:1299,duration:90},
      {id:"s3",name:"Keratin Treatment",price:3999,duration:180},
      {id:"s4",name:"Body Polishing",price:2499,duration:90},
      {id:"s5",name:"Threading (Full Face)",price:129,duration:20},
      {id:"s6",name:"Hair Colour",price:1999,duration:90},
    ],
    hours:"9:00 AM – 9:30 PM", phone:"+91 98860 33002",
    image:"/Images/YLG.jpeg",
    gallery:["/Images/YLG.jpeg","/Images/YLG.jpeg","/Images/YLG.jpeg"],
    about:"YLG's most popular outlet serving Electronic City's IT professionals.",
    openNow:true,
  },
  {
    id:"straight-sanjaynagar", name:"Straight Salon", branch:"Sanjay Nagar", area:"Sanjay Nagar",
    address:"Sanjay Nagar, Bangalore 560094",
    rating:4.8, reviewCount:4886, priceRange:"599",
    tags:["Hair","Colour","Smoothening"],
    services:[
      {id:"s1",name:"Haircut + Style",price:599,duration:45},
      {id:"s2",name:"Smoothening (Cysteine)",price:4999,duration:210},
      {id:"s3",name:"Keratin Treatment",price:5499,duration:210},
      {id:"s4",name:"Global Colour",price:2499,duration:120},
      {id:"s5",name:"Balayage",price:4499,duration:180},
      {id:"s6",name:"Hair Spa",price:1299,duration:60},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 10005",
    image:"/Images/Straight.jpeg",
    gallery:["/Images/Straight.jpeg","/Images/Straight.jpeg","/Images/Straight.jpeg"],
    about:"Bangalore's most-reviewed smoothening specialist — 4,886 reviews and 4.8★. Legendary for keratin and cysteine.",
    openNow:true,
  },

  // ── OTHER AREAS ─────────────────────────────────────────
  {
    id:"bodycraft-sadashivanagar", name:"Bodycraft Spa & Salon", branch:"Sadashivanagar", area:"Sadashivanagar",
    address:"Palace Road, Sadashivanagar, Bangalore 560080",
    rating:4.9, reviewCount:178, priceRange:"3499",
    tags:["Luxury","Bridal","Skin","Spa"],
    services:[
      {id:"s1",name:"Royal Bridal Package",price:45000,duration:600},
      {id:"s2",name:"Luxury Facial (Dermalogica)",price:4999,duration:90},
      {id:"s3",name:"Coffee Body Scrub",price:3999,duration:90},
      {id:"s4",name:"Hair Smoothening",price:5999,duration:180},
      {id:"s5",name:"Microblading (Eyebrows)",price:8999,duration:120},
      {id:"s6",name:"Hot Stone Massage",price:3499,duration:90},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22006",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"The crown jewel of Bodycraft in Bangalore — ultra-luxury treatments in an upscale setting.",
    openNow:true,
  },
  {
    id:"enrich-jpnagar", name:"Enrich Salon", branch:"JP Nagar", area:"JP Nagar",
    address:"3rd Phase, JP Nagar, Bangalore 560078",
    rating:4.3, reviewCount:201, priceRange:"399",
    tags:["Skin","Hair","Nails"],
    services:[
      {id:"s1",name:"Skin Brightening Facial",price:1299,duration:60},
      {id:"s2",name:"Haircut + Style",price:599,duration:45},
      {id:"s3",name:"Waxing (Full Body)",price:1299,duration:90},
      {id:"s4",name:"Nail Polish + Art",price:399,duration:30},
      {id:"s5",name:"Hair Spa",price:1199,duration:60},
      {id:"s6",name:"Eyelash Extension",price:1999,duration:90},
    ],
    hours:"10:00 AM – 8:30 PM", phone:"+91 98860 55003",
    image:"/Images/Enrich.jpeg",
    gallery:["/Images/Enrich.jpeg","/Images/Enrich.jpeg","/Images/Enrich.jpeg"],
    about:"Reliable chain salon in JP Nagar with consistent quality and great value.",
    openNow:false,
  },
  {
    id:"ylg-jpnagar", name:"YLG Salon", branch:"JP Nagar", area:"JP Nagar",
    address:"6th E Main Road, JP Nagar, Bangalore 560078",
    rating:4.4, reviewCount:176, priceRange:"549",
    tags:["Skin","Hair","Nails"],
    services:[
      {id:"s1",name:"YLG Signature Facial",price:1599,duration:75},
      {id:"s2",name:"Haircut",price:549,duration:40},
      {id:"s3",name:"Smoothening",price:3999,duration:180},
      {id:"s4",name:"Eyelash Extensions",price:1999,duration:90},
      {id:"s5",name:"De-Tan Body Pack",price:999,duration:60},
      {id:"s6",name:"Gel Nails",price:999,duration:60},
    ],
    hours:"9:00 AM – 9:00 PM", phone:"+91 98860 33004",
    image:"/Images/YLG.jpeg",
    gallery:["/Images/YLG.jpeg","/Images/YLG.jpeg","/Images/YLG.jpeg"],
    about:"YLG JP Nagar — quality skin care and hair services at affordable prices.",
    openNow:false,
  },
  {
    id:"bodycraft-jpnagar", name:"Bodycraft Spa & Salon", branch:"JP Nagar", area:"JP Nagar",
    address:"3rd Phase, JP Nagar, Bangalore 560078",
    rating:4.6, reviewCount:189, priceRange:"999",
    tags:["Luxury","Hair","Skin","Spa"],
    services:[
      {id:"s1",name:"Haircut & Styling",price:1299,duration:60},
      {id:"s2",name:"Skin Brightening Facial",price:3499,duration:90},
      {id:"s3",name:"Keratin Treatment",price:6499,duration:180},
      {id:"s4",name:"Waxing (Arms + Legs)",price:999,duration:60},
      {id:"s5",name:"Aromatherapy Massage",price:2999,duration:60},
      {id:"s6",name:"Nail Art",price:1499,duration:75},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22009",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"A beloved luxury destination for South Bangalore residents.",
    openNow:false,
  },
  {
    id:"barberco-richmond", name:"BarberCo", branch:"Richmond Town", area:"Richmond Town",
    address:"9 Myrtle Lane, Richmond Town, Bangalore 560025",
    rating:4.8, reviewCount:131, priceRange:"499",
    tags:["Men's","Hair","Grooming"],
    services:[
      {id:"s1",name:"Classic Gentleman's Cut",price:799,duration:45},
      {id:"s2",name:"Hot Towel Shave",price:699,duration:40},
      {id:"s3",name:"Beard Sculpting",price:599,duration:35},
      {id:"s4",name:"Hair + Beard Combo",price:1299,duration:75},
      {id:"s5",name:"Scalp Massage",price:499,duration:30},
      {id:"s6",name:"Hair Colour (Men)",price:1499,duration:60},
    ],
    hours:"9:00 AM – 8:00 PM", phone:"+91 98860 10007",
    image:"/Images/Barber CO.jpeg",
    gallery:["/Images/Barber CO.jpeg","/Images/Barber CO.jpeg","/Images/Barber CO.jpeg"],
    about:"Richmond Town's finest barbershop — classic cuts, hot towel shaves and old-school grooming rituals.",
    openNow:true,
  },
  {
    id:"bodycraft-frazertown", name:"Bodycraft Spa & Salon", branch:"Frazer Town", area:"Frazer Town",
    address:"Mosque Road, Frazer Town, Bangalore 560005",
    rating:4.7, reviewCount:211, priceRange:"1299",
    tags:["Luxury","Hair","Skin","Spa"],
    services:[
      {id:"s1",name:"Haircut + Blowdry",price:1299,duration:60},
      {id:"s2",name:"Facial (Ainhoa)",price:3999,duration:90},
      {id:"s3",name:"Body Massage",price:2999,duration:60},
      {id:"s4",name:"Waxing (Full Body)",price:1799,duration:90},
      {id:"s5",name:"Nail Extensions",price:1799,duration:90},
      {id:"s6",name:"Lash Lift + Tint",price:1999,duration:60},
    ],
    hours:"10:00 AM – 9:00 PM", phone:"+91 98860 22008",
    image:"/Images/Bodycraft.jpeg",
    gallery:["/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg","/Images/Bodycraft.jpeg"],
    about:"The original Bodycraft location — founded in 1999. A landmark of Bangalore's beauty industry.",
    openNow:true,
  },
  {
    id:"studio11-rajajinagar", name:"Studio 11 Salon", branch:"Rajajinagar", area:"Rajajinagar",
    address:"2nd Block, 1st Main Road, Rajajinagar, Bangalore 560010",
    rating:4.6, reviewCount:178, priceRange:"599",
    tags:["Hair","Bridal","Skin"],
    services:[
      {id:"s1",name:"Smoothening",price:4299,duration:180},
      {id:"s2",name:"Bridal Makeup",price:14999,duration:300},
      {id:"s3",name:"Fruit Facial",price:999,duration:60},
      {id:"s4",name:"Hair Cut + Style",price:599,duration:50},
      {id:"s5",name:"Waxing (Arms + Legs)",price:699,duration:50},
      {id:"s6",name:"Hair Colour",price:2299,duration:120},
    ],
    hours:"10:00 AM – 8:00 PM", phone:"+91 98860 10011",
    image:"/Images/Studio 11.jpeg",
    gallery:["/Images/Studio 11.jpeg","/Images/Studio 11.jpeg","/Images/Studio 11.jpeg"],
    about:"Trendy studio-style salon popular for bridal bookings and hair transformations.",
    openNow:false,
  },
  {
    id:"green-trends-banashankari", name:"Green Trends", branch:"Banashankari", area:"Banashankari",
    address:"2nd Stage, BSK 2nd Block, Banashankari, Bangalore 560070",
    rating:4.3, reviewCount:189, priceRange:"249",
    tags:["Hair","Skin","Men's"],
    services:[
      {id:"s1",name:"Women's Haircut",price:449,duration:40},
      {id:"s2",name:"Men's Haircut",price:249,duration:30},
      {id:"s3",name:"Global Colour",price:2299,duration:120},
      {id:"s4",name:"Basic Facial",price:799,duration:45},
      {id:"s5",name:"Head Massage",price:349,duration:30},
      {id:"s6",name:"Hair Spa",price:799,duration:45},
    ],
    hours:"9:30 AM – 9:00 PM", phone:"+91 98860 10008",
    image:"/Images/Green Trends.jpeg",
    gallery:["/Images/Green Trends.jpeg","/Images/Green Trends.jpeg","/Images/Green Trends.jpeg"],
    about:"Trusted neighbourhood salon — 25+ years of quality and consistency at affordable prices.",
    openNow:true,
  },
];

export const MOCK_REVIEWS = {
  "bodycraft-indiranagar":[
    {id:"r1",user:"Priya R.",rating:5,text:"Absolutely the best salon in Bangalore. My bridal experience was flawless!",date:"2025-02-10"},
    {id:"r2",user:"Anitha K.",rating:5,text:"Dermalogica facial was incredible. Skin glowing for days!",date:"2025-01-22"},
  ],
  "jcb-koramangala":[
    {id:"r1",user:"Deepa S.",rating:5,text:"Balayage turned out exactly how I wanted. The colourist is a genius!",date:"2025-02-05"},
  ],
  "straight-sanjaynagar":[
    {id:"r1",user:"Kavya B.",rating:5,text:"Best smoothening in Bangalore, hands down. Results lasted 6 months!",date:"2025-02-12"},
    {id:"r2",user:"Ritu V.",rating:5,text:"Visited for keratin — absolutely worth every rupee.",date:"2025-01-18"},
  ],
  "alchemic-indiranagar":[
    {id:"r1",user:"Sneha M.",rating:5,text:"Fantasy colour done beautifully. The stylist understood exactly what I wanted.",date:"2025-03-01"},
  ],
  "lakme-indiranagar":[
    {id:"r1",user:"Meena T.",rating:5,text:"Bridal makeup was stunning! The whole team made my wedding day perfect.",date:"2025-01-30"},
    {id:"r2",user:"Pooja N.",rating:4,text:"Great facial experience. Staff friendly and salon very clean.",date:"2025-01-05"},
  ],
};

export const AREAS = [
  "All areas","Indiranagar","Koramangala","Jayanagar","MG Road","Whitefield",
  "HSR Layout","Malleshwaram","Banashankari","Sadashivanagar","Electronic City",
  "Rajajinagar","Yelahanka","New BEL Road","JP Nagar","BTM Layout","Frazer Town",
  "HRBR Layout","Richmond Town","Sanjay Nagar","Kanakapura Road",
];

export const SERVICE_TAGS = [
  "All","Hair","Skin","Bridal","Nails","Organic","Men's","Luxury","Colour","Spa","Smoothening",
];